version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: maven
  directory: "/chat-getting-started-dropwizard"
  schedule:
    interval: weekly
- package-ecosystem: gradle
  directory: "/chat-getting-started-kotlin"
  schedule:
    interval: weekly