version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  reviewers:
      - "lfgcampos"
  schedule:
    interval: weekly
- package-ecosystem: maven
  directory: "/chat-getting-started-dropwizard"
  reviewers:
      - "lfgcampos"
  schedule:
    interval: weekly
- package-ecosystem: gradle
  directory: "/chat-getting-started-kotlin"
  reviewers:
      - "lfgcampos"
  schedule:
    interval: weekly
