name: Axon Playground - chat-getting-started-kotlin

on: 
  push:
    paths: chat-getting-started-kotlin/**
  pull_request:
    paths: chat-getting-started-kotlin/**

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Cache .m2
        uses: actions/cache@v2.1.7
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build and verify
        working-directory: ./chat-getting-started-kotlin
        run: ./gradlew build