name: Axon Playground - chat-getting-started-dropwizard

on: [push, pull_request]
  paths: chat-getting-started-dropwizard/**

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set up JDK 11
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Cache .m2
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build and verify
        working-directory: chat-getting-started-dropwizard
        run: mvn -B -U clean verify