name: Axon Playground - chat-getting-started-kotlin

on: 
  push:
    paths: chat-getting-started-kotlin/**
  pull_request:
    paths: chat-getting-started-kotlin/**

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'maven'

      - name: Build and verify
        working-directory: ./chat-getting-started-kotlin
        run: ./gradlew build